### ISSUE TITLE
[Steam Version] Cannot click the big cookie

### ISSUE THREAD

**Issue by AFKoncore** [CookieMonsterTeam/CookieMonster#950] opened 2021-09-02 01:02 UTC
**Describe the bug**
When loading this mod on the Steam version and clicking the big cookie the animation plays fine but you get no cookie, the number of time clicked in the Stats tab does not increase.

**Browser**
Steam Version (Electron)

**Comment by Pyrite19** [comment] 2021-09-02 01:37
There is no steam version. Please do not report bugs from my port here, I am sorry for the issues, CookieMonsterTeam.

**Comment by AFKoncore** [comment] 2021-09-02 02:56
I'm talking about the Steam version of the game. I didn't use anyone's port, I just loaded the current version of CookieMonster into the Steam client.

**Comment by DanielNoord** [comment] 2021-09-02 06:21
I currently don't have the Steam version myself so I can't really investigate this. Does the game work besides the big cookie?

**Comment by TFHatGuy** [comment] 2021-09-02 06:27
> I currently don't have the Steam version myself so I can't really investigate this. Does the game work besides the big cookie?

It seems to from what I've seen of it – the bottom bar appears, and the colourings work on buildings as intended; though I hadn't bothered importing my web save to check on things like sounds or flashes, I imagine they would work fine too – though I wouldn't be 100% certain of that.

**Comment by AFKoncore** [comment] 2021-09-02 06:50
@DanielNoord I sent you a DM on reddit re: getting you the Steam version, if you want it.

**Comment by DanielNoord** [comment] 2021-09-02 08:05
See my response to your DM on reddit.

For others, I currently don't have access to a windows computer (only a Mac) so even with the game I wouldn't be able to test anything. When I get my hands on a windows computer I will try and fix these bugs asap.
In the meantime, if anybody wants to open a PR to try and fix some of the issues you are more than welcome to!

**Comment by Reaver01** [comment] 2021-09-02 14:10
> > I currently don't have the Steam version myself so I can't really investigate this. Does the game work besides the big cookie?
> 
> It seems to from what I've seen of it – the bottom bar appears, and the colourings work on buildings as intended; though I hadn't bothered importing my web save to check on things like sounds or flashes, I imagine they would work fine too – though I wouldn't be 100% certain of that.

Flashes work, sounds do not. 

Here's what I can gather rn on the clicking issue:

![image](https://user-images.githubusercontent.com/1864450/131851463-02b74e03-d8e3-4523-9221-9150c8995d4f.png)

It looks like e ends up undefined and breaks clicking.

![image](https://user-images.githubusercontent.com/1864450/131858959-97ebdc18-703a-4213-a395-39de754802e6.png)

It can technically be fixed by removing this section out of the if statement on line 4634 in main.js, but there is probably a better solution that I'm too tired to think of.

**Comment by Urganot** [comment] 2021-09-02 17:28
@Reaver01 hwo do you open the console ingame? I might be able to help but i have no idea how to debug it

**Comment by LeapingSheep** [comment] 2021-09-02 17:54
> @Reaver01 hwo do you open the console ingame? I might be able to help but i have no idea how to debug it

steamapps\common\Cookie Clicker\resources\app
Edit start.js and at line 7 change false to true.

**Comment by Urganot** [comment] 2021-09-02 18:24
The problem seems to be the eventhandler itself. for some reason it is called but doesnt receive the event.
![image](https://user-images.githubusercontent.com/5991022/131896756-eb0c60a2-342a-447f-ac5b-54a093fc8213.png)

**Comment by Urganot** [comment] 2021-09-02 18:28
When executing AddEvent(bigCookie,'click',Game.ClickCookie); in the console, the handler will be called twice. the first time e is undefined the second time e is populated.
Maybe the AddEvent(bigCookie,'click',Game.ClickCookie); (line 4713) is too early in the lifecycle?

**Comment by Urganot** [comment] 2021-09-02 19:28
@DanielNoord The problem lies int he FixMouseY function
after being initialized here
![image](https://user-images.githubusercontent.com/5991022/131904450-40b6e8a2-0d17-4abf-8b3d-09eaf9629e7b.png)
The function then calls the Game.CookieClicked eventhandler
![image](https://user-images.githubusercontent.com/5991022/131904496-c1620096-5e27-446e-9181-89cbc8eef9b3.png)
In the end the event doesnt reach the Game.ClickCookie method

I dont know js well enough to fix this though

**Comment by Urganot** [comment] 2021-09-02 19:40
They changed the code here from the web game in the web its 
![image](https://user-images.githubusercontent.com/5991022/131905919-eccf7ec6-c507-486a-8abb-9d16ba0d60fb.png)
while in steam its
![image](https://user-images.githubusercontent.com/5991022/131905964-e26a6307-765b-47dc-91e5-df4127690fb0.png)

**Comment by Urganot** [comment] 2021-09-02 20:20
I think i fixed it. I opened PR #953 
ypu can test it by using  https://urganot.github.io/CookieMonster/dist/CookieMonsterDev.js as the source
![image](https://user-images.githubusercontent.com/5991022/131910654-20eb4986-8478-4056-a273-0f2de184e3c5.png)

Version warning is not fixed

**Comment by LeapingSheep** [comment] 2021-09-02 20:22
❤️ Its working with your CookieMonsterdev.js!!!

**Comment by DanielNoord** [comment] 2021-09-02 20:53
Going to push this ASAP! Thanks for your amazing and quick work here @Urganot

**Comment by DanielNoord** [comment] 2021-09-02 21:02
Closed with #953, let me know if there are any problems accessing it from the normal link!

**Closed by DanielNoord** 2021-09-02 21:02 UTC
Labels: Bug
